### ISSUE TITLE
Not sure how to get subscriptions server working

### ISSUE THREAD

**Issue by JohannesKlauss** [MichalLytek/typegraphql-nestjs#13]
I am trying to get subscriptions going with this package, but there seems to be something off or missing.
This is my Module instance:

```ts
TypeGraphQLModule.forRootAsync({
      imports: [AuthModule, DynamicRedisModule],
      inject: [CookieStrategy, RedisService],
      useFactory: async (cookieStrategy: CookieStrategy, redisService: RedisService) => {
        return {
          validate: true,
          dateScalarMode: 'timestamp',
          playground: false,
          authChecker: cookieAuthChecker,
          path: '/',
          emitSchemaFile: true,
          uploads: false,
          globalMiddlewares: [GqlAuthGuard(), ReplaceMe()],
          context: async ({ request }): Promise<GraphQLContext> => ({
            prisma,
            user: await cookieStrategy.validate(request),
          }),
          cors: {
            origin: [/* urls... */],
            credentials: true,
          },
          pubSub: new RedisPubSub({
            publisher: redisService.getClient('publisher'),
            subscriber: redisService.getClient('subscriber'),
          }),
          installSubscriptionHandlers: true,
        };
      },
    }),
```

Starting up the server throws the following error:

```
(node:6923) UnhandledPromiseRejectionWarning: TypeError: this.apolloServer.installSubscriptionHandlers is not a function
    at GraphQLModule.<anonymous> (/Users/johannesklauss/Documents/Development/Syra/node_modules/@nestjs/graphql/dist/graphql.module.js:97:35)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/johannesklauss/Documents/Development/Syra/node_modules/@nestjs/graphql/node_modules/tslib/tslib.js:111:62)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Although the nestjs docs state that `installSubscriptionHandlers` is a boolean: https://docs.nestjs.com/graphql/subscriptions#enable-subscriptions

I guess I have to pass a function but I don't know which one. Can you help out here?

**Comment by MichalLytek** [comment]
Are you able to reproduce that using the `@nestjs/graphql`?

`typegraphql-nestjs` is a wrapper around that library and doesn't do anything related to apollo-server nor subscriptions.

**Comment by JohannesKlauss** [comment]
Yes the same happens with the standard package.

```ts
GraphQLModule.forRoot({
      installSubscriptionHandlers: true,
      typePaths: [__dirname + '/../../schema.gql']
    }),
```

So I guess this is a nestjs bug then?

**Comment by MichalLytek** [comment]
Correct! So please ask for support there and then reopen this issue if fixed upstream and still doesn't work here after updating deps 😉

**Comment by JohannesKlauss** [comment]
Actually it was a dependency issue, I am using fastify apollo server in v3 alpha which caused the problem.

**Comment by ogheo** [comment]
@JohannesKlauss have you found a solution?
