### ISSUE TITLE
0.3.0 breaks compilation with current Nest.js version

### ISSUE THREAD

**Issue by JohannesKlauss** [MichalLytek/typegraphql-nestjs#17]
Using the 0.3.0 version of this package breaks compilation with the following error:

```
Nest can't resolve dependencies of the TypeGraphQLOptionsFactory (TYPEGRAPHQL_ROOT_MODULE_OPTIONS, ?). Please make sure that the argument OptionsPreparatorService at index [1] is available in the GraphQLModule context.

Potential solutions:
- If OptionsPreparatorService is a provider, is it part of the current GraphQLModule?
- If OptionsPreparatorService is exported from a separate @Module, is that module imported within GraphQLModule?
  @Module({
    imports: [ /* the Module containing OptionsPreparatorService */ ]
  })
 +1ms
Error: Nest can't resolve dependencies of the TypeGraphQLOptionsFactory (TYPEGRAPHQL_ROOT_MODULE_OPTIONS, ?). Please make sure that the argument OptionsPreparatorService at index [1] is available in the GraphQLModule context.

Potential solutions:
- If OptionsPreparatorService is a provider, is it part of the current GraphQLModule?
- If OptionsPreparatorService is exported from a separate @Module, is that module imported within GraphQLModule?
  @Module({
    imports: [ /* the Module containing OptionsPreparatorService */ ]
  })

    at Injector.lookupComponentInParentModules (/Users/johannesklauss/Documents/Development/Syra/node_modules/@nestjs/core/injector/injector.js:188:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Injector.resolveComponentInstance (/Users/johannesklauss/Documents/Development/Syra/node_modules/@nestjs/core/injector/injector.js:144:33)
    at async resolveParam (/Users/johannesklauss/Documents/Development/Syra/node_modules/@nestjs/core/injector/injector.js:98:38)
    at async Promise.all (index 1)
    at async Injector.resolveConstructorParams (/Users/johannesklauss/Documents/Development/Syra/node_modules/@nestjs/core/injector/injector.js:113:27)
    at async Injector.loadInstance (/Users/johannesklauss/Documents/Development/Syra/node_modules/@nestjs/core/injector/injector.js:46:9)
    at async Injector.loadProvider (/Users/johannesklauss/Documents/Development/Syra/node_modules/@nestjs/core/injector/injector.js:68:9)
    at async Promise.all (index 13)
    at async InstanceLoader.createInstancesOfProviders (/Users/johannesklauss/Documents/Development/Syra/node_modules/@nestjs/core/injector/instance-loader.js:43:9)

Process finished with exit code 130 (interrupted by signal 2: SIGINT)
```

These are my used nest packages:
```
    "@nestjs-modules/mailer": "1.5.1",
    "@nestjs/bull": "0.3.1",
    "@nestjs/common": "7.6.15",
    "@nestjs/config": "0.6.3",
    "@nestjs/core": "7.6.15",
    "@nestjs/graphql": "7.10.3",
    "@nestjs/jwt": "7.2.0",
    "@nestjs/microservices": "7.6.15",
    "@nestjs/passport": "7.1.5",
    "@nestjs/platform-fastify": "7.6.15",
```

**Comment by MichalLytek** [comment]
Sorry, forgot to update `TypeGraphQLModule` as well 😞 

Should be fixed in 0.3.1 🔒
